Dev
impash/qa-automation-java pull request #11
Opened 2021-09-05 08:32 UTC by impash

Удалил старые тесты, 
переписал логику сохранения записей в сервисе, 
в репо данные стали храниться в массиве,
добавил методы для работы с записями в репо: getStatus, changeStatus

2021-09-06 10:04 UTC, TikhomirovSergey requested changes

2021-09-06 10:04 UTC, TikhomirovSergey commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    public void getLoanRequestStatusByUUID() {
Общее замечание к тестам:
1. Тест должен строиться по схеме A(arrange)A(act)A(assert). 
Т.е. все действия в рамках теста можно разделить на 3 группы 
 - подготовка (повторяющиеся можно выносить в фикстуры) 
 - выполнение 
 - проверка результата, которая либо проходит, либо выбразывает AssertError

2. Каждый тест должен быть атомарным. Т.е. один тестовый метод проверяет ТОЛЬКО ОДИН кейс.

2021-09-06 10:13 UTC, TikhomirovSergey requested changes

2021-09-06 10:13 UTC, TikhomirovSergey commented on src/main/java/com/tinkoff/edu/app/service/LoanCalcService.java
> +        if (request.getType().equals(LoanUserType.PERSON) & request.getAmount() <= 10_000 & request.getMonths() <= 12) {
Во первых в задании требовалось сделать через  switch
Во вторых даже если идти через if - то можно лучше

if (условие PERSON) {
    //проверка выполнения условий  для PERSON
}
else if (условие OOO) {
   //проверка выполнения условий  для OOO
}
else {
   //проверка выполнения условий  для IP
}

Кстати, switch можно построить по конструкции выше

2021-09-06 10:13 UTC, TikhomirovSergey commented on src/main/java/com/tinkoff/edu/app/service/LoanCalcService.java
> +        if (request.getType().equals(LoanUserType.PERSON) & request.getAmount() <= 10_000 & request.getMonths() <= 12) {
А вот тут кстати можно использовать == вместо equals. Погуглить

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/controller/LoanCalcController.java
> +    LoanRepositoryImpl repo = new LoanRepositoryImpl();
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/controller/LoanCalcController.java
> +        if ((request.getFio().length() < 10) || (request.getFio().length() > 100)) {
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/controller/LoanCalcController.java
> +        System.out.println("\n_ВЫПОЛНЕН ЗАПРОС по UUID: " + uuid + "\n");
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/service/LoanCalcService.java
> +        UUID uuid = UUID.randomUUID();
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/dao/LoanRepositoryImpl.java
> +            if ((loanRequestRecords[i] != null) && (loanRequestRecords[i].getUuid() == uuid)) {
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/dao/LoanRepositoryImpl.java
> +        return loanRequestRecords[number];
обсудили, переписал логику

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/dao/LoanRepositoryImpl.java
> +            if ((loanRequestRecord != null) && (loanRequestRecord.getUuid() == uuid)) {
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/service/LoanCalcService.java
> +    public LoanRequestRecord getStatus(UUID uuid) {
done

2021-09-09 23:50 UTC, impash commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    public void getLoanRequestStatusByUUID() {
done

2021-09-09 23:50 UTC, impash commented on src/main/java/com/tinkoff/edu/app/service/LoanCalcService.java
> +        if (request.getType().equals(LoanUserType.PERSON) & request.getAmount() <= 10_000 & request.getMonths() <= 12) {
done

2021-09-10 09:01 UTC, TikhomirovSergey approved these changes

2021-09-10 09:02 UTC, merged